In [145]:
import torch
import torch.nn as nn # ngambil neural network, ngambil loss function
import torch.optim as optim # Ngambil optimizer
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [146]:
iris = load_iris()
X = iris.data
y = iris.target

In [147]:
x

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [148]:
scaler = MinMaxScaler()
x = scaler.fit_transform(X)

In [149]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [150]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [151]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [152]:
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long) # long long int -> bentuk int lebih gede
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

In [153]:
model = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 3),
    # nn.Softmax() 
)

In [154]:
loss_fun = nn.CrossEntropyLoss() # include Softmax()
optimizer = optim.Adam(model.parameters(), lr=0.1)

### Feed Forward -> Compute Loss -> Back Propagation


In [163]:
print(len(y))

150


In [155]:
epochs = 50
for epoch in range(epochs):
    optimizer.zero_grad() # gradient descent ke reset
    outputs = model(X_train)
    loss = loss_fun(outputs, y_train)
    loss.backward()
    optimizer.step() # menjalankan gradient descent

    with torch.no_grad():
        test_outputs = model(X_test)
        _, predicted = torch.max(test_outputs, 1) # _ = abaikan
        acc = (predicted == y_test).sum() / len(y_test)

    print(f'Epoch-{epoch + 1}/{epochs}. Loss: {loss.item():.4f}. Test Acc: {acc*100:.4f}%')

Epoch-1/50. Loss: 1.1423. Test Acc: 33.3333%
Epoch-2/50. Loss: 1.1975. Test Acc: 33.3333%
Epoch-3/50. Loss: 1.1123. Test Acc: 33.3333%
Epoch-4/50. Loss: 1.0979. Test Acc: 33.3333%
Epoch-5/50. Loss: 1.0845. Test Acc: 33.3333%
Epoch-6/50. Loss: 1.0703. Test Acc: 33.3333%
Epoch-7/50. Loss: 1.0448. Test Acc: 33.3333%
Epoch-8/50. Loss: 1.0027. Test Acc: 36.6667%
Epoch-9/50. Loss: 0.9398. Test Acc: 66.6667%
Epoch-10/50. Loss: 0.8811. Test Acc: 66.6667%
Epoch-11/50. Loss: 0.8190. Test Acc: 66.6667%
Epoch-12/50. Loss: 0.7673. Test Acc: 66.6667%
Epoch-13/50. Loss: 0.7309. Test Acc: 66.6667%
Epoch-14/50. Loss: 0.6803. Test Acc: 76.6667%
Epoch-15/50. Loss: 0.6454. Test Acc: 96.6667%
Epoch-16/50. Loss: 0.6251. Test Acc: 96.6667%
Epoch-17/50. Loss: 0.5938. Test Acc: 76.6667%
Epoch-18/50. Loss: 0.5595. Test Acc: 73.3333%
Epoch-19/50. Loss: 0.5412. Test Acc: 73.3333%
Epoch-20/50. Loss: 0.5226. Test Acc: 76.6667%
Epoch-21/50. Loss: 0.4947. Test Acc: 86.6667%
Epoch-22/50. Loss: 0.4768. Test Acc: 96.666

In [156]:
iris = load_iris()
X = iris.data
y = iris.target

In [157]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [158]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [159]:
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

In [160]:
model = nn.Sequential(
    nn.Linear(4, 8),   # x * W + B  # input 4 -> hidden 8
    nn.ReLU(),
    nn.Linear(8, 3)    # hidden 8 -> output 3 (kelas)
)

In [161]:
loss_fun = nn.CrossEntropyLoss() # include softmax
optimizer = optim.SGD(model.parameters(), lr=0.1)  # Gradient Descent (SGD)

In [162]:
epochs = 500
for epoch in range(epochs):
    # Forward + backward + update
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = loss_fun(outputs, y_train)
    loss.backward()
    optimizer.step()
    
    # Evaluasi test set
    with torch.no_grad():
        test_outputs = model(X_test)
        _, predicted = torch.max(test_outputs, 1)
        acc = (predicted == y_test).sum().item() / len(y_test)
    
    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}, Test Acc: {acc*100:.2f}%")

Epoch 1/500, Loss: 1.0914, Test Acc: 33.33%
Epoch 2/500, Loss: 1.0869, Test Acc: 33.33%
Epoch 3/500, Loss: 1.0824, Test Acc: 33.33%
Epoch 4/500, Loss: 1.0780, Test Acc: 33.33%
Epoch 5/500, Loss: 1.0737, Test Acc: 33.33%
Epoch 6/500, Loss: 1.0695, Test Acc: 33.33%
Epoch 7/500, Loss: 1.0655, Test Acc: 33.33%
Epoch 8/500, Loss: 1.0615, Test Acc: 33.33%
Epoch 9/500, Loss: 1.0575, Test Acc: 33.33%
Epoch 10/500, Loss: 1.0535, Test Acc: 33.33%
Epoch 11/500, Loss: 1.0495, Test Acc: 33.33%
Epoch 12/500, Loss: 1.0456, Test Acc: 36.67%
Epoch 13/500, Loss: 1.0417, Test Acc: 40.00%
Epoch 14/500, Loss: 1.0378, Test Acc: 43.33%
Epoch 15/500, Loss: 1.0338, Test Acc: 43.33%
Epoch 16/500, Loss: 1.0299, Test Acc: 43.33%
Epoch 17/500, Loss: 1.0259, Test Acc: 50.00%
Epoch 18/500, Loss: 1.0218, Test Acc: 53.33%
Epoch 19/500, Loss: 1.0178, Test Acc: 63.33%
Epoch 20/500, Loss: 1.0137, Test Acc: 70.00%
Epoch 21/500, Loss: 1.0095, Test Acc: 73.33%
Epoch 22/500, Loss: 1.0053, Test Acc: 70.00%
Epoch 23/500, Loss: