# Numpy Part 1: Numpy Fundamentals and Essentials

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../Data/Iris.csv')

In [42]:
df['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
iris_data_numeric = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values

### Numpy Array

In [7]:
python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)

In [8]:
print(python_list)
print(array_from_list)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [9]:
array_from_list[1]

np.int64(2)

In [10]:
# np.zeros()
zeros_array = np.zeros((3, 3, 3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# np.ones
ones_array = np.ones((3, 3, 3))
ones_array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
# np.arange() -> similar with for loop (start, stop, step?) for i in range
arange_array = np.arange(0, 20, 2)
arange_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Random value numpy array
np.random.rand() -> random float  
np.random.randint() -> random int

In [13]:
random_float_array = np.random.rand(5, 5)
random_float_array

array([[0.30154732, 0.50744423, 0.20856189, 0.03029964, 0.03951408],
       [0.51098358, 0.77118435, 0.07595547, 0.53640955, 0.37712829],
       [0.06454041, 0.9084948 , 0.49693819, 0.754724  , 0.76366481],
       [0.78951873, 0.93412615, 0.03014611, 0.05468576, 0.79613878],
       [0.89741822, 0.87910412, 0.72083296, 0.75481534, 0.97020354]])

In [14]:
random_int_array = np.random.randint(0, 10, size=(3, 3))
random_int_array

array([[6, 1, 8],
       [9, 1, 9],
       [3, 1, 1]], dtype=int32)

### Reshaping array

In [15]:
old_array = np.arange(1, 11) # 1 x 10
old_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
old_array_reshaped = old_array.reshape(5, 2)
old_array_reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Indexing and Slicing

In [17]:
iris_data_numeric[0, 0]

np.float64(5.1)

In [18]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [19]:
# [row, column] -> [start:end:step, start:end:step]
iris_data_numeric[0:5, 0:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [20]:
iris_data_numeric[:, -2:] # -1

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [21]:
sepal_length_gt_5 = iris_data_numeric[iris_data_numeric[:, 0] > 5.0]

In [22]:
sepal_length_gt_5

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2

### Operasi Numpy (Aritmatika & Aggregation)

In [23]:
data15 = np.arange(1, 6)
data510 = np.arange(6, 11)

In [24]:
data15.shape

(5,)

In [25]:
data510.shape

(5,)

In [26]:
data_sum = data15 * 5

In [27]:
data_sum

array([ 5, 10, 15, 20, 25])

In [28]:
data_substrac = data510 - data15

In [29]:
data_substrac


array([5, 5, 5, 5, 5])

# Numpy Part 2: Broadcasting

In [30]:
# np.sqrt()

In [34]:
data = np.random.randint(10, 100, size=(3, 3))
data

array([[94, 89, 62],
       [48, 15, 50],
       [10, 16, 45]], dtype=int32)

In [ ]:
Data_sqrt = np.sqrt(data)
Data_sqrt

array([[9.69535971, 9.43398113, 7.87400787],
       [6.92820323, 3.87298335, 7.07106781],
       [3.16227766, 4.        , 6.70820393]])

In [ ]:
# np.log
data_log = np.log(data)
data_log

array([[4.54329478, 4.48863637, 4.12713439],
       [3.87120101, 2.7080502 , 3.91202301],
       [2.30258509, 2.77258872, 3.80666249]])

In [41]:
data_log_2 = np.log2(data)
data_log_2

array([[6.55458885, 6.47573343, 5.95419631],
       [5.5849625 , 3.9068906 , 5.64385619],
       [3.32192809, 4.        , 5.4918531 ]])

In [ ]:
# np.exp(), np.sin(), np.cos()

### Dot Product & Matrix Multiplication

In [43]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [44]:
# np.dot
hasil = np.dot(v1, v2)
hasil

np.int64(32)

In [47]:
m1 = np.array([[2, 3, 1],
               [7, 6, 1]])

m2 = np.array([[1, 2],
               [5, 3],
               [1, 1]])

In [ ]:
hasil = np.dot(m1, m2)
hasil

array([[18, 14],
       [38, 33]])

In [50]:
hasil = m1 @ m2
hasil

array([[18, 14],
       [38, 33]])

In [52]:
hasil = np.matmul(m1, m2)
hasil

array([[18, 14],
       [38, 33]])

### Broadcasting

In [ ]:
# numpy, pytorch -> ga sama

In [ ]:
# vector dengan scalar
v = np.array([1, 2, 3])
s = 10

hasil = v + s

In [54]:
hasil

array([11, 12, 13])

In [ ]:
# matrix dengan vector
M = np.array([[1, 2,  3], # c = 3
              [4, 5, 6]]) # r = 5

v = np.array([[10],
              [20]]) # v = 4
# len(v) == 1 -> scalar
# len(v.column) == c
# len(v.row) == r

hasil = M + v

In [79]:
hasil

array([[11, 12, 13],
       [24, 25, 26]])

In [67]:
M = np.array([[1, 2, 3], 
              [4, 5, 6]])
v = np.array([[100],
              [200]])

hasil = M + v

In [65]:
hasil

array([[101, 102, 103],
       [204, 205, 206]])

In [69]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [72]:
iris_data_numeric_tambahan = iris_data_numeric[:, 3] + 0.5
iris_data_numeric_tambahan

array([0.7, 0.7, 0.7, 0.7, 0.7, 0.9, 0.8, 0.7, 0.7, 0.6, 0.7, 0.7, 0.6,
       0.6, 0.7, 0.9, 0.9, 0.8, 0.8, 0.8, 0.7, 0.9, 0.7, 1. , 0.7, 0.7,
       0.9, 0.7, 0.7, 0.7, 0.7, 0.9, 0.6, 0.7, 0.6, 0.7, 0.7, 0.6, 0.7,
       0.7, 0.8, 0.8, 0.7, 1.1, 0.9, 0.8, 0.7, 0.7, 0.7, 0.7, 1.9, 2. ,
       2. , 1.8, 2. , 1.8, 2.1, 1.5, 1.8, 1.9, 1.5, 2. , 1.5, 1.9, 1.8,
       1.9, 2. , 1.5, 2. , 1.6, 2.3, 1.8, 2. , 1.7, 1.8, 1.9, 1.9, 2.2,
       2. , 1.5, 1.6, 1.5, 1.7, 2.1, 2. , 2.1, 2. , 1.8, 1.8, 1.8, 1.7,
       1.9, 1.7, 1.5, 1.8, 1.7, 1.8, 1.8, 1.6, 1.8, 3. , 2.4, 2.6, 2.3,
       2.7, 2.6, 2.2, 2.3, 2.3, 3. , 2.5, 2.4, 2.6, 2.5, 2.9, 2.8, 2.3,
       2.7, 2.8, 2. , 2.8, 2.5, 2.5, 2.3, 2.6, 2.3, 2.3, 2.3, 2.6, 2.1,
       2.4, 2.5, 2.7, 2. , 1.9, 2.8, 2.9, 2.3, 2.3, 2.6, 2.9, 2.8, 2.4,
       2.8, 3. , 2.8, 2.4, 2.5, 2.8, 2.3])

### np.concatenate

In [85]:
array1 = np.array([[1, 2], 
                   [3, 4]])

array2 = np.array([[5, 6]])

array_gabungan = np.concatenate((array1, array2), axis=0)
array_gabungan
# axis 0 = rows
# axis 1 = columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
array1 = np.array([[1, 2], 
                   [3, 4]])

array2 = np.array([[5],
                   [6]])

# kalau kita paksain pakai axis 0
# np.array([[1, 2], 
#           [3, 4]
#           [5],
#           [6]
# ])

array_gabungan = np.concatenate((array1, array2), axis=1)
array_gabungan


array([[1, 2, 5],
       [3, 4, 6]])