# Numpy Part 1: Numpy Fundamentals and Essentials

In [61]:
import numpy as np
import pandas as pd

In [63]:
df = pd.read_csv('../Data/Iris.csv')

In [64]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [67]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [109]:
iris_data_numeric = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values

### Numpy Array

In [71]:
python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)

In [73]:
print(python_list)
print(array_from_list)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [74]:
array_from_list[1]

np.int64(2)

In [86]:
# np.zeros()
zeros_array = np.zeros((3, 3, 3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [88]:
# np.ones
ones_array = np.ones((3, 3, 3))
ones_array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [91]:
# np.arange() -> similar with for loop (start, stop, step?) for i in range
arange_array = np.arange(0, 20, 2)
arange_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Random value numpy array
np.random.rand() -> random float  
np.random.randint() -> random int

In [94]:
random_float_array = np.random.rand(5, 5)
random_float_array

array([[0.5023074 , 0.6630911 , 0.84784756, 0.49490894, 0.54368478],
       [0.67090048, 0.8055349 , 0.0764473 , 0.11595059, 0.98750851],
       [0.31977724, 0.52700729, 0.62901455, 0.74817476, 0.34786568],
       [0.68578081, 0.36847654, 0.02212522, 0.388298  , 0.81962594],
       [0.56999569, 0.44448885, 0.92801833, 0.15574721, 0.48279907]])

In [99]:
random_int_array = np.random.randint(0, 10, size=(3, 3))
random_int_array

array([[7, 1, 9],
       [0, 1, 4],
       [2, 5, 8]], dtype=int32)

### Reshaping array

In [ ]:
old_array = np.arange(1, 11) # 1 x 10
old_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
old_array_reshaped = old_array.reshape(5, 2)
old_array_reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Indexing and Slicing

In [110]:
iris_data_numeric[0, 0]

np.float64(5.1)

In [111]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
# [row, column] -> [start:end:step, start:end:step]
iris_data_numeric[0:5, 0:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [130]:
iris_data_numeric[:, -2:] # -1

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [131]:
sepal_length_gt_5 = iris_data_numeric[iris_data_numeric[:, 0] > 5.0]

In [132]:
sepal_length_gt_5

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2

### Operasi Numpy (Aritmatika & Aggregation)

In [139]:
data15 = np.arange(1, 6)
data510 = np.arange(6, 11)

In [140]:
data15.shape

(5,)

In [141]:
data510.shape

(5,)

In [151]:
data_sum = data15 * 5

In [152]:
data_sum

array([ 5, 10, 15, 20, 25])

In [145]:
data_substrac = data510 - data15

In [146]:
data_substrac


array([5, 5, 5, 5, 5])

In [126]:
import numpy as np
import pandas as pd

In [127]:
df = pd.read_csv('../Data/Iris.csv')

In [128]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
iris_data_numeric= df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values

### Numpy array

In [8]:
python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)
print(python_list)
print(array_from_list)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [9]:
array_from_list[1]

np.int64(2)

In [16]:
zeros_array = np.zeros((3, 2))
print(zeros_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
ones_array = np.ones((4, 5))
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# konsep for loop in range
arange_array = np.arange(0, 10, 2)
arange_array

array([0, 2, 4, 6, 8])

In [29]:
random_float_array = np.random.rand(2, 2)
random_float_array

array([[0.8509611 , 0.14425804],
       [0.26294461, 0.99243482]])

In [35]:
random_int_array = np.random.randint(0, 100, size=(3, 3), dtype='int64')
random_int_array

array([[36, 66, 31],
       [70, 67, 99],
       [87, 14, 87]])

### Reshaping an Array

In [38]:
old_array = np.arange(0, 10)
old_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
old_array_reshaped = old_array.reshape(2, 5)
old_array_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Indexing and Array Slicing

In [44]:
single_element = iris_data_numeric[0, 0]
single_element

np.float64(5.1)

In [49]:
iris_data_numeric.shape

(150, 4)

In [50]:
iris_data_numeric[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
iris_data_numeric[0:5, ]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [59]:
iris_data_numeric[:, [0, 2]]

array([[5.1, 1.4],
       [4.9, 1.4],
       [4.7, 1.3],
       [4.6, 1.5],
       [5. , 1.4],
       [5.4, 1.7],
       [4.6, 1.4],
       [5. , 1.5],
       [4.4, 1.4],
       [4.9, 1.5],
       [5.4, 1.5],
       [4.8, 1.6],
       [4.8, 1.4],
       [4.3, 1.1],
       [5.8, 1.2],
       [5.7, 1.5],
       [5.4, 1.3],
       [5.1, 1.4],
       [5.7, 1.7],
       [5.1, 1.5],
       [5.4, 1.7],
       [5.1, 1.5],
       [4.6, 1. ],
       [5.1, 1.7],
       [4.8, 1.9],
       [5. , 1.6],
       [5. , 1.6],
       [5.2, 1.5],
       [5.2, 1.4],
       [4.7, 1.6],
       [4.8, 1.6],
       [5.4, 1.5],
       [5.2, 1.5],
       [5.5, 1.4],
       [4.9, 1.5],
       [5. , 1.2],
       [5.5, 1.3],
       [4.9, 1.5],
       [4.4, 1.3],
       [5.1, 1.5],
       [5. , 1.3],
       [4.5, 1.3],
       [4.4, 1.3],
       [5. , 1.6],
       [5.1, 1.9],
       [4.8, 1.4],
       [5.1, 1.6],
       [4.6, 1.4],
       [5.3, 1.5],
       [5. , 1.4],
       [7. , 4.7],
       [6.4, 4.5],
       [6.9,

In [60]:
sepal_length_gt_5 = iris_data_numeric[iris_data_numeric[:, 0] > 5.0]

### Operasi dasar pada array (Aritmathic & Aggregation)